In [37]:
from sklearn.cluster import KMeans
import numpy as np

X = np.array([[5.9,3.2],[4.6,2.9],[6.2,2.8],[4.7,3.2],[5.5,4.2],[5.0,3.0],[4.9,3.1],[6.7,3.1],[5.1,3.8],[6.0,3.0]])

initial_clusters= np.array([[6.2,3.2],[6.5,3.0],[6.6,3.7]])

kmeans = KMeans(n_clusters=3, random_state=0,init=initial_clusters,max_iter=3).fit(X)
kmeans.labels_


C:\Users\bruna\Anaconda3\lib\site-packages\sklearn\cluster\k_means_.py:896: RuntimeWarning: Explicit initial center position passed: performing only one init in k-means instead of n_init=10
  return_n_iter=True)


array([1, 0, 1, 0, 2, 0, 0, 1, 2, 1])

In [38]:
kmeans.predict(X)



array([1, 0, 1, 0, 2, 0, 0, 1, 2, 1])

In [39]:
kmeans.cluster_centers_


array([[ 4.8  ,  3.05 ],
       [ 6.2  ,  3.025],
       [ 5.3  ,  4.   ]])

In [ ]:
http://www.inf.unibz.it/~zini/ML/slides/ml_2012_lecture_10.pdf